security:
  enable_authenticator_manager: true

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      context: my_context
      custom_authenticators:
        - App\Security\LdapAuthenticator

    main:
      pattern: ^/api
      stateless: true
      context: my_context
      custom_authenticators:
        - App\Security\TokenAuthenticator

  access_control:
    # allow unauthenticated users to access the login form
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }

    # but require authentication for all other admin routes
    - { path: ^/admin, roles: ROLE_ADMIN }
