version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: office
    ports:
    - 4406:3306

  mail:
    image: mailhog/mailhog
    ports:
    - 8025:8025

  app:
    container_name: office_app
    image: webdevops/php-apache:8.0
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    links:
      - mail:mail
      - database:mysql
      - ldap:ldap
    volumes:
    - .:/app
    ports:
    - 8090:80

  ldap:
    image: rroemhild/test-openldap
