version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: office
    ports:
    - 127.0.0.1:4406:3306

  mail:
    image: mailhog/mailhog
    ports:
    - 127.0.0.1:8025:8025

  app:
    container_name: office_app
    image: webdevops/php-apache:8.0
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      SIMPLESAMLPHP_CONFIG_DIR: /app/config
      AUTH_SERVICE: saml
    links:
      - mail:mail
      - database:mysql
      - ldap:ldap
    volumes:
    - .:/app
    ports:
    - 127.0.0.1:8090:80

  ldap:
    image: rroemhild/test-openldap

  saml:
    image: kristophjunge/test-saml-idp
    ports:
      - "18080:8080"
      - "18443:8443"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:18080/simplesaml/saml2/idp/metadata.php
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8090/api/saml/callback