# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: 'user_mapping.yml' }
    - { resource: 'user_mapping.yml', ignore_errors: true }

parameters:
    floor_path: '/maps'
    saml.metadata_fallback: ''
    saml.metadata_url: '%env(default:saml.metadata_fallback:SAML_METADATA_URL)%'
    frontend.url_fallback: 'http://localhost:9999'
    frontend.url: '%env(default:frontend.url_fallback:FRONTEND_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Repository\CriteriaBuilder\CriteriaBuilder:
            tags: ['criteria.builder']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Exception/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Repository\CriteriaFactory:
        arguments:
            $builders: !tagged_iterator criteria.builder

    App\Ldap\LdapProvider:
        arguments:
            $server: '%env(LDAP_SERVER)%'
            $searchFilter: '%env(LDAP_SEARCH_FILTER)%'
            $bindDn: '%env(LDAP_BIND_DN)%'
            $baseDn: '%env(LDAP_BASE_DN)%'

    App\User\UserMapper:
        arguments:
            $authService: '%external.auth_service%'
            $userMappings: '%user_mappings%'

    App\Request\ErrorResponseFactory:
        arguments:
            $debug: '%kernel.debug%'

    App\File\FileHandler:
        arguments:
            $mapDirectory: '%floor_path%'
            $publicFolder: '%kernel.project_dir%/public'

    App\Security\LdapAuthenticator:
        arguments:
            $authService: '%external.auth_service%'

    App\Security\SamlAuthenticator:
        arguments:
            $authService: '%external.auth_service%'
            $frontendUrl: '%frontend.url%'

    App\Command\ImportMetaDataCommand:
        arguments:
            $metaDataUrl: '%saml.metadata_url%'
            $metaDataFileName: '%kernel.project_dir%/metadata/saml20-idp-remote.php'
