parameters:
  external.auth_service_fallback: "saml"
  external.auth_service: '%env(default:external.auth_service_fallback:AUTH_SERVICE)%'

  user_mappings:
    ldap:
      id: "cn"
      email: "mail"
      display_name: "displayname"
      full_name: "cn"
      roles: "ou"
      image: "jpegphoto"
    saml:
      id: "uid"
      email: "email"
      display_name: "displayname"
      full_name: "full_name"
      roles: "eduPersonAffiliation"
      image: "jpegphoto"
