parameters:
  external.auth_service_fallback: "saml"
  external.auth_service: '%env(default:external.auth_service_fallback:AUTH_SERVICE)%'

  user_mapping_fallbacks.ldap.id: "cn"
  user_mapping_fallbacks.ldap.email: "mail"
  user_mapping_fallbacks.ldap.display_name: "displayname"
  user_mapping_fallbacks.ldap.full_name: "cn"
  user_mapping_fallbacks.ldap.roles: "ou"
  user_mapping_fallbacks.ldap.image: "jpegphoto"

  user_mapping_fallbacks.saml.id: "uid"
  user_mapping_fallbacks.saml.email: "email"
  user_mapping_fallbacks.saml.display_name: "displayname"
  user_mapping_fallbacks.saml.full_name: "full_name"
  user_mapping_fallbacks.saml.roles: "eduPersonAffiliation"
  user_mapping_fallbacks.saml.image: "jpegphoto"

  user_mappings:
    ldap:
      id: "%env(default:user_mapping_fallbacks.ldap.id:AUTH_SERVICE_MAPPING_ID)%"
      email: "%env(default:user_mapping_fallbacks.ldap.email:AUTH_SERVICE_MAPPING_EMAIL)%"
      display_name: "%env(default:user_mapping_fallbacks.ldap.display_name:AUTH_SERVICE_MAPPING_DISPLAY_NAME)%"
      full_name: "%env(default:user_mapping_fallbacks.ldap.full_name:AUTH_SERVICE_MAPPING_FULL_NAME)%"
      roles: "%env(default:user_mapping_fallbacks.ldap.roles:AUTH_SERVICE_MAPPING_ROLES)%"
      image: "%env(default:user_mapping_fallbacks.ldap.image:AUTH_SERVICE_MAPPING_IMAGE)%"
    saml:
      id: "%env(default:user_mapping_fallbacks.saml.id:AUTH_SERVICE_MAPPING_ID)%"
      email: "%env(default:user_mapping_fallbacks.saml.email:AUTH_SERVICE_MAPPING_EMAIL)%"
      display_name: "%env(default:user_mapping_fallbacks.saml.display_name:AUTH_SERVICE_MAPPING_DISPLAY_NAME)%"
      full_name: "%env(default:user_mapping_fallbacks.saml.full_name:AUTH_SERVICE_MAPPING_FULL_NAME)%"
      roles: "%env(default:user_mapping_fallbacks.saml.roles:AUTH_SERVICE_MAPPING_ROLES)%"
      image: "%env(default:user_mapping_fallbacks.saml.image:AUTH_SERVICE_MAPPING_IMAGE)%"
